default: &default
  adapter: postgresql
  encoding: unicode
  user: web
  password: 123
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graphql_development
  
test:
  <<: *default
  database: graphql_test
  
production:
  <<: *default
  database: graphql_production
